name: Build and Deploy Docker Image

on: [push]

jobs:
  test:
    name: Run Junit Test
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: "mariadb:10.10"
        ports:
          - "3306:3306"
        env:
          MARIADB_ROOT_PASSWORD: "password"
        
    steps:
    - uses: actions/checkout@v2
    - name: "Init Java 17"
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      run: |
        mvn --quiet test

  build-and-deploy:
    name: "Build Docker Image and deploy to Registry"
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build -t docker.pkg.github.com/bbzblit/m426-api/app:latest .
    - name: Login to GitHub Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin
    - name: Push Docker Image
      run: |
        docker push docker.pkg.github.com/bbzblit/m426-api/app:latest